# Why arent the melt values created by square_melt_region using differnt melt_magnitudes exact multiples of each other?

In [1]:
import xarray as xr
import hvplot.xarray
import numpy as np 

In [4]:
results = xr.open_dataset('results_small_test.nc')
x_resolution = results.x[1].values - results.x[0].values
assert x_resolution == np.abs(results.y[1].values - results.y[0].values)
resolution = x_resolution
cell_area = resolution**2

In [5]:
total_melt = (results['melt']*cell_area).sum(dim=['x','y'])
total_melt.name = 'total_melt'
total_melt.attrs['units'] = 'm3'
total_melt
total_melt.isel(melt_magnitude=1, x_center_of_melt=0)/

<xarray.DataArray 'total_melt' (x_center_of_melt: 2, melt_magnitude: 2)>
array([[ 4984060.5, 49840128. ],
       [ 4984060.5, 49840128. ]], dtype=float32)
Coordinates:
  * x_center_of_melt  (x_center_of_melt) float64 8.125e+05 8.175e+05
  * melt_magnitude    (melt_magnitude) float64 0.2 2.0
Attributes:
    units:    m3

The following should be exactly 10, but it isnt. 

In [7]:
total_melt.isel(melt_magnitude=1, x_center_of_melt=0)/total_melt.isel(melt_magnitude=0, x_center_of_melt=0)

<xarray.DataArray 'total_melt' ()>
array(9.999905, dtype=float32)
Coordinates:
    x_center_of_melt  float64 8.125e+05

The total number of cells with non-zero melt are the same:

In [9]:
(results['melt']>0).sum(dim=['x','y'])

<xarray.DataArray 'melt' (x_center_of_melt: 2, melt_magnitude: 2)>
array([[24336, 24336],
       [24336, 24336]])
Coordinates:
  * x_center_of_melt  (x_center_of_melt) float64 8.125e+05 8.175e+05
  * melt_magnitude    (melt_magnitude) float64 0.2 2.0

The mean of the melt values in areas that a non-zeron melt is 2 in the case of melt_magnitude=2 (as required), but not equal to 0.2 in the case of melt_magnitude=0.2. I dont know why.

In [10]:
results['melt'].where(results['melt']>0).mean(dim=['x','y'])

<xarray.DataArray 'melt' (x_center_of_melt: 2, melt_magnitude: 2)>
array([[0.20000191, 2.        ],
       [0.20000191, 2.        ]], dtype=float32)
Coordinates:
  * x_center_of_melt  (x_center_of_melt) float64 8.125e+05 8.175e+05
  * melt_magnitude    (melt_magnitude) float64 0.2 2.0

In [13]:
(results['melt']==0.2).sum(dim=['x','y'])

<xarray.DataArray 'melt' (x_center_of_melt: 2, melt_magnitude: 2)>
array([[24336,     0],
       [24336,     0]])
Coordinates:
  * x_center_of_melt  (x_center_of_melt) float64 8.125e+05 8.175e+05
  * melt_magnitude    (melt_magnitude) float64 0.2 2.0

In [15]:
(results['melt']!=0).sum(dim=['x','y'])

<xarray.DataArray 'melt' (x_center_of_melt: 2, melt_magnitude: 2)>
array([[24336, 24336],
       [24336, 24336]])
Coordinates:
  * x_center_of_melt  (x_center_of_melt) float64 8.125e+05 8.175e+05
  * melt_magnitude    (melt_magnitude) float64 0.2 2.0